In [1]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("../dataset/v2.csv")
df.size

FileNotFoundError: [Errno 2] No such file or directory: '../dataset/v3.csv'

In [ ]:
df.head()

,shop_id,shop_name,province,week_number,product_name,category,quantity_sold
0,1,Colombo Fresh,Western,1,Rice,Staple,130
1,1,Colombo Fresh,Western,1,Rice Flour,Staple,78
2,1,Colombo Fresh,Western,1,Wheat Flour,Staple,57
3,1,Colombo Fresh,Western,1,Sugar,Staple,94
4,1,Colombo Fresh,Western,1,Coconut Oil,Staple,77

In [ ]:
df['shop_id'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76])

In [ ]:
df['product_name'].unique()

<StringArray>
[            'Rice',       'Rice Flour',      'Wheat Flour',
            'Sugar',      'Coconut Oil',             'Dhal',
              'Tea',      'Milk Powder',            'Bread',
             'Eggs',  'Instant Noodles',         'Biscuits',
      'Soft Drinks',    'Energy Drinks',   'Washing Powder',
             'Soap',          'Shampoo',          'Candles',
           'Snacks',    'Bottled Water', 'Stationery Items',
   'Festival Goods']
Length: 22, dtype: str

In [ ]:
df['province'].unique()

<StringArray>
[      'Western',       'Central',      'Southern',      'Northern',
       'Eastern', 'North Western', 'North Central',           'Uva',
  'Sabaragamuwa']
Length: 9, dtype: str

In [ ]:
unique_shops_by_province = df.groupby('province')['shop_id'].nunique().reset_index()
unique_shops_by_province.columns = ['province', 'unique_shop_count']

In [ ]:
unique_shops_by_province

        province  unique_shop_count
0        Central                  6
1        Eastern                  9
2  North Central                 10
3  North Western                  6
4       Northern                  8
5   Sabaragamuwa                  9
6       Southern                  9
7            Uva                  9
8        Western                 10

In [ ]:
len(df)

43472